site_name: InvArch Docs
site_url: https://docs.invarch.com/
repo_url: https://github.com/InvArch/InvArch-docs/
site_description: "InvArch Documentation and Resources"
site_author: "InvArch Team"
theme:
    name: material
    palette:
        primary: purple
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.top
plugins:
    - search

nav:
    - Learn:
        - 'Platform':
            - 'Welcome': 'index.md'
            - 'Vision': 'vision.md'
            - 'Why Polkadot': 'why-polkadot.md'
            - 'Roadmap': 'roadmap.md'
            - 'Networks': 'networks.md'
            - 'Technology': 'technology.md'
            - 'Tokens': 'tokens.md'
            - 'Source Code': 'source-code.md'
            - 'Important Links': 'important-links.md'
            - 'Glossary': 'glossary.md'
        - 'Features': 
            - 'Protocol': 'protocol.md'
    - 'Node Operators': 
        - 'Getting Started': 'node-operators.md'
    - Builders: 
        - 'Start Build': 'builders.md'
