site_name: InvArch Docs
site_url: https://docs.invarch.com/
nav:
    - Home: index.md
    - Learn: learn.md
    - Node Operators: node-operators.md
    - Builders: builders.md
theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  icon:
    logo: logo
