name: CheckMkDocsBuild
on:
  # Trigger the workflow on a new pull request on master
  pull_request_target:
    branches:
      - main

jobs:
  build-docs-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout Submodule
        run: |
          git submodule update --init

      - name: Allow to move dotfiles
        run: |
          # move also dotfile with *
          shopt -s dotglob

      - name: Move InvArch-docs contents to mkdocs repository
        run: |
          mkdir InvArch-mkdocs/InvArch-docs
          mv * InvArch-mkdocs/InvArch-docs &> /dev/null || echo "Error with mv expected due to recursively moving all contents into subfolder"

      - name: Install pip requirements
        run: |
          cd InvArch-mkdocs
          # upgrade pip
          pip3 install --upgrade pip setuptools
          # install dependencies quietly
          pip3 install -r requirements.txt &> /dev/null && echo "Dependencies installed" || echo "Error while installing dependencies"

      - name: Build mkdocs
        run: |
          cd InvArch-mkdocs
          # change destination build folder in mkdocs YAML to local site/
          sed -i "s/'site_dir'.*/'site_dir': 'site'/" mkdocs.yml
          # build project
          python3 -m mkdocs build